version: "3"

services:
  app:
    build: .
    ports:
    - "8080:3000"
    volumes:
      - .:/app/src/

  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=momento-tec
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=senhasecreta
    ports:
      - "9000:80"
    depends_on:
      - db
